### ISSUE TITLE
Doesn't work for webworkers

### ISSUE THREAD

**Issue by rhwilburn** [dmitru/console-log-img#1]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Doesn't work for webworkers due to dependency on HTMLCanvasElement**

Webworkers don't have access to HTML element types, and so logging hits issues with those. I made a small work around intially (see below), however even it eventually needs to use a canvas type to push the image to. That causes things to fall over.

`var window = self;
var document = self;
window['HTMLImageElement'] = <any>function(){};
window['HTMLCanvasElement'] = <any>function(){};
window['HTMLCanvasElement'] = <any>function(){};`

Ideally a pollyfill could be added for webworker style situations that don't have DOM access? Perhaps something like: https://github.com/casperlamboo/canvas-webworker (perhaps also something like this?: https://github.com/danielhusar/fake-dom/blob/master/index.js)

My usecase is to use offscreen canvas, but that ultimately depends on canvas in the library. Ideally Offscreencanvas could be the first if statement (avoiding mocking of those HTML types completely) and then canvas somehow polyfilled.

The library works well for me otherwise for large images (it serves them at the speed of video 👍 which is impressive )

**Comment by rhwilburn** [comment]
See here: https://justadudewhohacks.github.io/face-api.js/docs/index.html (with their monkeyPatch) method thats mentioned. It shows how they stub canvas etc for node environements (ie non dom).

**Comment by dmitru** [comment]
Hey, thanks for reporting the issue.
v 4.0.1 now supports OffscreenCanvas and should work with WebWorkers (although I haven't tested it).
