### ISSUE TITLE
Undefined type for "OffscreenCanvas" and "CanvasRenderingContext2D"

### ISSUE THREAD

**Issue by d-c-mate** [dmitru/console-log-img#2]
Thanks for your awesome package !

- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I'm using Ionic-Angular and i've found undefined types in the package.
in the file : src/lib/console-extensions.ts
Can't find the types : "OffscreenCanvas" and "CanvasRenderingContext2D", it's deprecated or something like this with Angular 13 

![image_2022-06-13_025951851](https://user-images.githubusercontent.com/24377043/173261711-99efca6e-2acb-49a9-9c17-d9aef1ddbd99.png)

**Comment by dmitru** [comment]
It really depends on your TypeScript environment; I'd recommend simply declaring these types somewhere in your code as aliases to HTMLCanvasElement and CanvasRenderingContext2D as a workaround.
Hope it helps!
